[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
solc = "0.8.19"
optimizer = true
optimizer_runs = 200

[profile.default.optimizer_details]
yul = true
yulDetails = { stackAllocation = true, optimizerSteps = "dhfoDgvulfnTUtnIf" }

[profile.default.model_checker]
contracts = { "contracts/strategies/SandwichExecutor.sol" = [], "contracts/core/FlashLoanHandler.sol" = [], "contracts/utils/PriceOracle.sol" = [] }
engine = "chc"
timeout = 10000
targets = ["assert", "divByZero", "underflow", "overflow", "outOfBounds"]

[rpc_endpoints]
polygon = "${POLYGON_RPC_URL}"
polygon_fork = "http://localhost:8545"

[etherscan]
polygon = { key = "${POLYGONSCAN_API_KEY}" }
