[package]
name = "sandwich-strategy"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
mev-rs = { git = "https://github.com/ralexstokes/mev-rs" }
mev-core = { path = "../../core" }
mev-math = { path = "../../math" }
tokio = { version = "1.0", features = ["full"] }
